//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemAmenity
    {
        public int ID { get; set; }
        public System.Guid GUID { get; set; }
        public int ItemID { get; set; }
        public int AmenityID { get; set; }
    
        public virtual Amenity Amenity { get; set; }
        public virtual Item Item { get; set; }
    }
}
