//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.ItemAmenities = new HashSet<ItemAmenity>();
            this.ItemAttractions = new HashSet<ItemAttraction>();
        }
    
        public int ID { get; set; }
        public System.Guid GUID { get; set; }
        public int UserID { get; set; }
        public int ItemTypeID { get; set; }
        public int AreaID { get; set; }
        public string Title { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> NumberOfBeds { get; set; }
        public Nullable<int> NumberOfBedrooms { get; set; }
        public Nullable<int> NumberOfBathrooms { get; set; }
        public string ExactAddress { get; set; }
        public string ApproximateAddress { get; set; }
        public string Description { get; set; }
        public string HostRules { get; set; }
        public Nullable<int> MinimumNights { get; set; }
        public Nullable<int> MaximumNights { get; set; }
    
        public virtual Area Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemAmenity> ItemAmenities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemAttraction> ItemAttractions { get; set; }
        public virtual ItemType ItemType { get; set; }
        public virtual User User { get; set; }
    }
}
