//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemAttraction
    {
        public int ID { get; set; }
        public System.Guid GUID { get; set; }
        public int ItemID { get; set; }
        public int AttractionID { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public Nullable<int> DurationOnFoot { get; set; }
        public Nullable<int> DurationByCar { get; set; }
    
        public virtual Attraction Attraction { get; set; }
        public virtual Item Item { get; set; }
    }
}
