//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetail
    {
        public int ID { get; set; }
        public System.Guid GUID { get; set; }
        public int BookingID { get; set; }
        public int ItemPriceID { get; set; }
        public bool IsRefund { get; set; }
        public Nullable<System.DateTime> RefundDate { get; set; }
        public Nullable<int> RefundCancellationPolicyID { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual ItemPrice ItemPrice { get; set; }
    }
}
