//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimDate
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Quarter { get; set; }
        public Nullable<int> Month { get; set; }
        public string MonthName { get; set; }
        public Nullable<int> DayOfMonth { get; set; }
        public Nullable<int> DayOfWeek { get; set; }
        public string DayName { get; set; }
        public bool IsHoliday { get; set; }
    }
}
