//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIS2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArrangementStation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArrangementStation()
        {
            this.OpenStations = new HashSet<OpenStation>();
        }
    
        public int Id { get; set; }
        public int StoreId { get; set; }
        public int MaximumPeople { get; set; }
        public bool IsEnable { get; set; }
    
        public virtual Store Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpenStation> OpenStations { get; set; }
    }
}
