//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIS2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenStation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OpenStation()
        {
            this.OrderFlowers = new HashSet<OrderFlower>();
        }
    
        public int Id { get; set; }
        public int StationId { get; set; }
        public int NumberOfPeople { get; set; }
        public bool HasVase { get; set; }
        public System.DateTime OpenTime { get; set; }
        public bool IsCheckout { get; set; }
        public Nullable<System.DateTime> CheckOutTime { get; set; }
        public decimal TotalAmount { get; set; }
    
        public virtual ArrangementStation ArrangementStation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderFlower> OrderFlowers { get; set; }
    }
}
