//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIS2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderFlower
    {
        public int Id { get; set; }
        public int OpenStationId { get; set; }
        public int FlowerId { get; set; }
        public int Number { get; set; }
        public System.DateTime OrderTime { get; set; }
    
        public virtual Flower Flower { get; set; }
        public virtual OpenStation OpenStation { get; set; }
    }
}
