//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIS2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public string StaffId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public int RoleId { get; set; }
        public int StoreId { get; set; }
        public string Photo { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Store Store { get; set; }
    }
}
